### ISSUE TITLE
AttributeError: module 'tensorflow_hub.tf_v1' has no attribute 'estimator'

### ISSUE THREAD

**Issue by csirmazbendeguz** [GantMan/nsfw_model#167]
Hello, I'm getting the following error when importing `nsfw_detector`:

```
  File "/MY_DIR/main.py", line 4, in <module>
    from nsfw_detector import predict
  File "/MY_DIR/venv/lib/python3.12/site-packages/nsfw_detector/predict.py", line 11, in <module>
    import tensorflow_hub as hub
  File "/MY_DIR/venv/lib/python3.12/site-packages/tensorflow_hub/__init__.py", line 29, in <module>
    from tensorflow_hub.estimator import LatestModuleExporter
  File "/MY_DIR/venv/lib/python3.12/site-packages/tensorflow_hub/estimator.py", line 64, in <module>
    class LatestModuleExporter(tf_v1.estimator.Exporter):
                               ^^^^^^^^^^^^^^^
AttributeError: module 'tensorflow_hub.tf_v1' has no attribute 'estimator'
```

```
> pip freeze
nsfw-detector==1.1.1
tensorboard==2.20.0
tensorboard-data-server==0.7.2
tensorflow==2.20.0
tensorflow-hub==0.7.0
```

```
> python --version
Python 3.12.5
```

**Comment by csirmazbendeguz** [comment]
It works with `tensorflow-hub==0.16.0`

Is there a reason `tensorflow-hub==0.12.0` is hardcoded in [requirements.txt](https://github.com/GantMan/nsfw_model/blob/699b6796a55604341fbfdffe2b27ced1d868c591/requirements.txt#L3)?

Is this library maintained at all?
